### ISSUE TITLE
Access token from browser to server side using cors

### ISSUE THREAD

**Issue by Shurpop** [Xabaril/JWTSimpleServer#13]
Hi, when we are doing the request of token from our frontend is possible to fetch the data but the response throws the error No 'Access-Control-Allow-Origin'.

Error: 
Access to XMLHttpRequest at 'http://localhost:53348/Token' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

If in the WriteResponseAsync we set the header with => context.Response.Headers["Access-Control-Allow-Origin"] = "*";  we can fetch the data correctly.

private Task WriteResponseAsync(
            int statusCode,
            HttpContext context,
            string content = "",
            string contentType = "application/json")
        {
            context.Response.Headers["Content-Type"] = contentType;
            context.Response.StatusCode = statusCode;
            return context.Response.WriteAsync(content);
        }

Thanks!

**Comment by CarlosLanderas** [comment]
Thanks @Shurpop, let me add a registration action to configure the pipeline middlewares and update the version

**Comment by CarlosLanderas** [comment]
@Shurpop, I have added a new configurePipeline parameter so you can register CORS in the JWTSimpleServer middleware branch

Sample:

public void ConfigureServices(IServiceCollection services)
        {
            services.AddSingleton<IAuthenticationProvider, CustomAuthenticationProvider>()
            .AddCors()
            .AddJwtSimpleServer(setup =>
            {
                setup.IssuerSigningKey = SigningKey;
            })
            .AddJwtInMemoryRefreshTokenStore()
            .AddMvcCore().
            AddAuthorization();
        }
        
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.UseDefaultFiles();
            app.UseStaticFiles();

            app.UseJwtSimpleServer(setup =>
            {
                setup.IssuerSigningKey = SigningKey;
            }, pipeline => {

                pipeline.UseCors(setup =>
                {
                    setup.AllowAnyOrigin().AllowAnyHeader().AllowAnyMethod();
                });
            });

            app.UseMvc();
        }
