### ISSUE TITLE
Great! your Token. i want change Expires

### ISSUE THREAD

**Issue by touchduck** [Xabaril/JWTSimpleServer#7]
i want change this in option. please.

public Func<DateTime> Expires = () => DateTime.UtcNow.AddMinutes(15);

**Comment by lurumad** [comment]
Hi @touchduck 

You can do this overriding this Func in the middleware configuration:

```csharp
.UseJwtSimpleServer(options => 
                {
                    options.IssuerSigningKey = "yoursigninkey";
                    options.Expires = () => DateTime.UtcNow.AddMinutes(60);
                });
```

Regards!

**Comment by CarlosLanderas** [comment]
Yeah @touchduck. That public Func<DateTime> is the default time given by the library. You can override with your own time :)

**Comment by touchduck** [comment]
wow, great! i can do it. 👍
