### ISSUE TITLE
how can use  async ValidateClientAuthenticationAsync

### ISSUE THREAD

**Issue by touchduck** [Xabaril/JWTSimpleServer#8]
thank u.

how can

 async ValidateClientAuthenticationAsync ??

`public async Task ValidateClientAuthenticationAsync(JwtSimpleServerContext context)
        {
            var user = await _userManager.FindByNameAsync(context.UserName);

            if (user == null)
            {
                context.Reject("Invalid user authentication");
            }

            var signInResult = await _signInManager.CheckPasswordSignInAsync(user, context.Password, false);

            if (signInResult.Succeeded)
            {
                var claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.Name, "demo"));

                context.Success(claims);
            } else {
                context.Reject("Invalid user authentication");
            }

            return Task.CompletedTask;
        }`

**Comment by CarlosLanderas** [comment]
```
  if (user == null)
        {
            context.Reject("Invalid user authentication");
        }
```

That code block above is not preventing the code below to execute. Use conditional statements to avoid it.

You can see this sample in the documentation:

```
public class CustomAuthenticationProvider : IAuthenticationProvider
{
    public Task ValidateClientAuthentication(JwtSimpleServerContext context)
    {
        if(context.UserName == "demo" && context.Password == "demo")
        {
            var claims = new List<Claim>();
            claims.Add(new Claim(ClaimTypes.Name, "demo"));

            context.Success(claims);
        }
        else
        {
            context.Reject("Invalid user authentication");
        }
        
        return Task.CompletedTask;            
    }
```

**Comment by touchduck** [comment]
sorry, it's different.
i using asp.net core Identity Manager ( it using user of ef core database )
so, i want login in 
var user = await _signInManager.CheckPasswordSignInAsync(user, context.Password, false);
because, this need  async await.
so i can not use my user of db.
T_T

**Comment by touchduck** [comment]
and. i set role.

  var claims = new List<Claim>();
                claims.Add(new Claim(ClaimTypes.Name, "demo"));
                claims.Add(new Claim(ClaimTypes.Role, Roles.ROLE_DUCKUSER));


but i can't call this. so , i think login to _signInManager
[Route("api/[controller]")]
[Authorize(Roles = "MYROLE")]
    public class ValuesController : Controller
    {
        // GET api/values
        [HttpGet]
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

**Comment by CarlosLanderas** [comment]
Are you receiving the access token from the middleware and setting it to the Authorization header using Bearer?

**Comment by touchduck** [comment]
yes, i can using.
Authorization : Bearer mytoken

**Comment by CarlosLanderas** [comment]
Is ROLE_DUCKUSER constant "MYROLE" ?

**Comment by touchduck** [comment]
yes ROLE_DUCKUSER is constant  = "MYROLE" 
i can try. thank u
