### ISSUE TITLE
Allow getting the token using email and password

### ISSUE THREAD

**Issue by pmorelli92** [Xabaril/JWTSimpleServer#9]
The `IAuthenticationProvider` should be flexible for those scenarios where the user may not login using the username but an email and password. 

I know that with the current implementation I can just make the clients send the email in the "username" and it will work but it is not nice for the clients to do that.

**Comment by CarlosLanderas** [comment]
The username can be used with an email as well, is up to the implementation validating looking for username, email or other identification
